# Generated by Django 6.0.3 on 2026-04-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothbrandapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
